#include "ocppConfiguration.h"

const char* CONFIG_KEY_STR_ALLOW_OFLINE_TX_FOR_UNKNOWN_ID     = "AllowOfflineTxForUnknownId";
const char* CONFIG_KEY_STR_AUTHORIZATION_CACHE_ENABLED        = "AuthorizationCacheEnabled";
const char* CONFIG_KEY_STR_AUTHORIZE_REMOTE_TX_REQUESTS       = "AuthorizeRemoteTxRequests";
const char* CONFIG_KEY_STR_BLINK_REPEAT                       = "BlinkRepeat";
const char* CONFIG_KEY_STR_CLOCK_ALIGNED_DATA_INTERVAL        = "ClockAlignedDataInterval";
const char* CONFIG_KEY_STR_CONNECTION_TIMEOUT                 = "ConnectionTimeOut";
const char* CONFIG_KEY_STR_CONNECTOR_PHASE_ROTATION           = "ConnectorPhaseRotation";
const char* CONFIG_KEY_STR_CONNECTOR_PHASE_ROTATION_MAX_LENGH = "ConnectorPhaseRotationMaxLength";
const char* CONFIG_KEY_STR_GET_CONFIGURATION_MAX_KEYS         = "GetConfigurationMaxKeys";
const char* CONFIG_KEY_STR_HEARTBEAT_INTERVAL                 = "HeartbeatInterval";
const char* CONFIG_KEY_STR_LIGHT_INTENSITY                    = "LightIntensity";

extern const char* EMPTY_STRING;

const char *ocppGetConfigKeyString(int configKey){

#define CASE_CONFIG_KEY_STR(name) case CONFIG_KEY_##name: \
	                                res = CONFIG_KEY_STR_##name; \
								    break

	const char* res = EMPTY_STRING;

	switch(configKey){	
		CASE_CONFIG_KEY_STR(ALLOW_OFLINE_TX_FOR_UNKNOWN_ID);
		CASE_CONFIG_KEY_STR(AUTHORIZATION_CACHE_ENABLED);
		CASE_CONFIG_KEY_STR(AUTHORIZE_REMOTE_TX_REQUESTS);
		CASE_CONFIG_KEY_STR(BLINK_REPEAT);
		CASE_CONFIG_KEY_STR(CLOCK_ALIGNED_DATA_INTERVAL);
		CASE_CONFIG_KEY_STR(CONNECTION_TIMEOUT);
		CASE_CONFIG_KEY_STR(CONNECTOR_PHASE_ROTATION);
		CASE_CONFIG_KEY_STR(CONNECTOR_PHASE_ROTATION_MAX_LENGH);
		CASE_CONFIG_KEY_STR(GET_CONFIGURATION_MAX_KEYS);
		CASE_CONFIG_KEY_STR(HEARTBEAT_INTERVAL);
		CASE_CONFIG_KEY_STR(LIGHT_INTENSITY);
		//CASE_CONFIG_KEY_STR();
	}
	return res;
}



int occpGetConfigKeyFromString(const char* s){

#define CHECK_CONFIG_KEY(name) if(strcmp(s, CONFIG_KEY_STR_##name) == 0) \
		                     return CONFIG_KEY_##name;

	CHECK_CONFIG_KEY(ALLOW_OFLINE_TX_FOR_UNKNOWN_ID);
	CHECK_CONFIG_KEY(AUTHORIZATION_CACHE_ENABLED);
	CHECK_CONFIG_KEY(AUTHORIZE_REMOTE_TX_REQUESTS);
	CHECK_CONFIG_KEY(BLINK_REPEAT);
	CHECK_CONFIG_KEY(CLOCK_ALIGNED_DATA_INTERVAL);
	CHECK_CONFIG_KEY(CONNECTION_TIMEOUT);
	CHECK_CONFIG_KEY(CONNECTOR_PHASE_ROTATION);
	CHECK_CONFIG_KEY(CONNECTOR_PHASE_ROTATION_MAX_LENGH);
	CHECK_CONFIG_KEY(GET_CONFIGURATION_MAX_KEYS);
	CHECK_CONFIG_KEY(HEARTBEAT_INTERVAL);
	CHECK_CONFIG_KEY(LIGHT_INTENSITY);

	return CONFIG_KEY_UNKNOWN;
}