#include "ocpp.h"

#define LOCAL_AUTH_LIST_ENABLED true

#define LOCAL_AUTH_LIST_MAX_LENGTH 256

#define OCPP_PROFILE_MASK OCPP_PROFILE_MASK_CORE \
	    | OCPP_PROFILE_MASK_LOCAL_AUTH_LIST_MANAGEMENT
